# Generated by Django 6.0.1 on 2026-02-02 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sigil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('incantation', models.TextField()),
                ('image', models.ImageField(upload_to='sigils/')),
                ('is_burned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('burned_at', models.DateTimeField(blank=True, null=True)),
                ('created_lat', models.FloatField(blank=True, null=True)),
                ('created_long', models.FloatField(blank=True, null=True)),
                ('burned_lat', models.FloatField(blank=True, null=True)),
                ('burned_long', models.FloatField(blank=True, null=True)),
                ('layout_type', models.CharField(default='Unknown', max_length=50)),
                ('vertex_count', models.IntegerField(default=-1)),
                ('letter_assignment', models.TextField(default='[]')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
