# Generated by Django 6.0.1 on 2026-01-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigil',
            name='burned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sigil',
            name='burned_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sigil',
            name='burned_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sigil',
            name='created_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sigil',
            name='created_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
